doc_dict = {'Ano' : '',
            'Mês' : '',
            'Nº Processo' : '',
            'Nome' : '',
            'Género' : '',
            'Idade' : '',
            'Intervalo' : '',
            'Idade' : '',
            'Raça' : '',
            'Residência' : '',
            'Dias internamento' : '',
            'Intervalo Dias Internamento' : '',
            'Proveniência' : '',
            'Grupo Nosológico' : '',
            'Cod ICD 10' : '',
            '1º Diagnóstico ICD 10' : '',
            '1º diagnóstico' : '',
            'Grupo Nosológico' : '',
            'Cod ICD 10' : '',
            '2º Diagnóstico ICD 10' : '',
            '2º Diagnóstico' : '',
            'Grupo Nosológico' : '',
            'Cod ICD 10' : '',
            '3º Diagnóstico ICD 10' : '',
            '3º Diagnóstico' : '',
            '1ª Comorbilidade' : '',
            '2ª Comorbilidade' : '',
            'Outros diagnósticos' : '',
            'UCI' : '',
            'Destino' : '',
            'Caso Social' : '',
            'Referenciação à RNCCI | Modelo' : '',
            'Re-internamento (30dias) | Mesmo motivo?' : '',
            'Motivo de Reinternamento' : '',
            'MRSA/Acinetobacter/Klebsiella MR' : '',
            'Barthel	Charlson Index' : '',
            'Sobrevivência estimada a 10 anos' : '',
            'Observações' : ''}

month_dict = {
    '01': 'Janeiro',
    '02': 'Fevereiro',
    '03': 'Março',
    '04': 'Abril',
    '05': 'Maio',
    '06': 'Junho',
    '07': 'Julho',
    '08': 'Agosto',
    '09': 'Setembro',
    '10': 'Outubro',
    '11': 'Novembro',
    '12': 'Dezembro'  }

race_list = ['caucasiano', 'africano', 'negro', 'asiático', 'homem-lagosta']


